drop table if exists confirmation_token CASCADE;
drop table if exists role CASCADE;
drop table if exists user CASCADE;
drop sequence if exists hibernate_sequence;

create sequence hibernate_sequence start with 3 increment by 1;

create table confirmation_token (
	token_id bigint generated by default as identity,
	token varchar(255),
	created_date varchar(127),
	expiry_date varchar(127),
	user_id bigint not null,
	primary key (token_id)
);

create table role (
	role_id bigint generated by default as identity,
	role_name varchar(255),
	primary key (role_id)
);

create table user (
	user_id bigint not null,
	address varchar(512),
	city varchar(127),
	company_name varchar(127),
	creation_date varchar(127),
	email varchar(128) not null,
	first_name varchar(64),
	last_name varchar(64),
	mobile_number bigint,
	password varchar(1024),
	status varchar(64),
	username varchar(64) not null,
	role_id bigint not null,
	primary key (user_id)
);

alter table role add constraint UK_ROLE_ROLE_NAME unique (role_name);
alter table user add constraint UK_USER_EMAIL unique (email);
alter table user add constraint UK_USER_USER_NAME unique (username);

alter table confirmation_token add constraint FK_TOKEN_USER_ID foreign key (user_id) references user;
alter table user add constraint FK_USER_ROLE_ID foreign key (role_id) references role;